2023-09-07 15:00:25,979 - ERROR - Error while handling server response
Traceback (most recent call last):
  File "/home/scion/.vim/bundle/YouCompleteMe/python/ycm/client/base_request.py", line 254, in _JsonFromFuture
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/scion/.vim/bundle/YouCompleteMe/python/ycm/unsafe_thread_pool_executor.py", line 42, in run
    result = self.fn( *self.args, **self.kwargs )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scion/.vim/bundle/YouCompleteMe/python/ycm/client/base_request.py", line 173, in _MakeRequest
    return urlopen(
           ^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scion/.vim/bundle/YouCompleteMe/python/ycm/client/base_request.py", line 77, in HandleFuture
    return _JsonFromFuture( future )
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scion/.vim/bundle/YouCompleteMe/python/ycm/client/base_request.py", line 267, in _JsonFromFuture
    raise MakeServerException( json.loads( response_text ) )
ycmd.responses.ServerError: RuntimeError: No documentation available.
